### ISSUE TITLE
transcription halts if desktop.ini file ends up in dataset dir

### ISSUE THREAD

**Issue by mustbeinsane** [JarodMica/StyleTTS-WebUI#17]
Error below. Added some logging and it was getting stuck on desktop.ini file that was there because windows explorer likes to add them when only audio files are in a dir. deleting hidden file temp fix. be great to have it ignore non-audio files. 

Loaded Whisper model
Traceback (most recent call last):
  File "E:\StyleTTS-WebUI\runtime\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StyleTTS-WebUI\runtime\Lib\site-packages\gradio\route_utils.py", line 288, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StyleTTS-WebUI\runtime\Lib\site-packages\gradio\blocks.py", line 1931, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StyleTTS-WebUI\runtime\Lib\site-packages\gradio\blocks.py", line 1516, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StyleTTS-WebUI\runtime\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StyleTTS-WebUI\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "E:\StyleTTS-WebUI\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StyleTTS-WebUI\runtime\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "E:\StyleTTS-WebUI\runtime\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "E:\StyleTTS-WebUI\webui.py", line 351, in transcribe_other_language_proxy
    file_durations = [get_duration(os.path.join(chosen_directory, item)) for item in items if os.path.isfile(os.path.join(chosen_directory, item))]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StyleTTS-WebUI\webui.py", line 351, in <listcomp>
    file_durations = [get_duration(os.path.join(chosen_directory, item)) for item in items if os.path.isfile(os.path.join(chosen_directory, item))]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StyleTTS-WebUI\modules\tortoise_dataset_tools\audio_conversion_tools\split_long_file.py", line 13, in get_duration
    duration = float(duration_output.decode().strip())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'N/A'

**Comment by JarodMica** [comment]
Knew this would get me in trouble, I'll add this sanity check there. I had run into it but forgotten about it
