### ISSUE TITLE
Transcribe and process error 

### ISSUE THREAD

**Issue by jabbasami** [JarodMica/StyleTTS-WebUI#22]
Hello, thank you for this amazing work that you put in your work. please when i do transcribe i get this error. 
my audio is 2minutes long, .wav file. 

Traceback (most recent call last):
  File "D:\work\Ai\New folder (2)\StyleTTS-WebUI\venv\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\Ai\New folder (2)\StyleTTS-WebUI\venv\Lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\Ai\New folder (2)\StyleTTS-WebUI\venv\Lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\Ai\New folder (2)\StyleTTS-WebUI\venv\Lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\Ai\New folder (2)\StyleTTS-WebUI\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\Ai\New folder (2)\StyleTTS-WebUI\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\work\Ai\New folder (2)\StyleTTS-WebUI\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\Ai\New folder (2)\StyleTTS-WebUI\venv\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\work\Ai\New folder (2)\StyleTTS-WebUI\venv\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\work\Ai\New folder (2)\StyleTTS-WebUI\webui.py", line 314, in transcribe_other_language_proxy
    whisper_model = load_whisper_model(language=language, model_name=whisper_model)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\Ai\New folder (2)\StyleTTS-WebUI\webui.py", line 299, in load_whisper_model
    whisper_model = whisperx.load_model(model_name, device, download_root="whisper_models")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\Ai\New folder (2)\StyleTTS-WebUI\venv\Lib\site-packages\whisperx\asr.py", line 288, in load_model
    model = model or WhisperModel(whisper_arch,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\Ai\New folder (2)\StyleTTS-WebUI\venv\Lib\site-packages\faster_whisper\transcribe.py", line 133, in __init__
    self.model = ctranslate2.models.Whisper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.

**Comment by JarodMica** [comment]
It's an issue with whisperx, I'll add this as a switch that can be automatically done

**Comment by jabbasami** [comment]
> It's an issue with whisperx, I'll add this as a switch that can be automatically done

Ow, that's a fast reply bro. love your content on youtube keep it on. nice. how can i do this myself?

**Comment by JarodMica** [comment]
Whisper model, when you go to load it in the code, you can specify what compute type you wanna use. You can check the args parser here for it, but you wanna specify int8 for your GPU: 

https://github.com/m-bain/whisperX/blob/9e3a9e0e38fcec1304e1784381059a0e2c670be5/whisperx/transcribe.py#L13
