### ISSUE TITLE
PermissionError: [WinError 5] Access is denied (when transcribing)

### ISSUE THREAD

**Issue by 96webbjo** [JarodMica/StyleTTS-WebUI#27]
....
Saved segment 3 to training\me14-brereabbit-43mins\processed\run\dataset\wav_splits\file___1\file___1_segment_556.mp3
Saved segment 7 to training\me14-brereabbit-43mins\processed\run\dataset\wav_splits\file___1\file___1_segment_552.mp3
Saved segment 4 to training\me14-brereabbit-43mins\processed\run\dataset\wav_splits\file___1\file___1_segment_557.mp3
Saved segment 8 to training\me14-brereabbit-43mins\processed\run\dataset\wav_splits\file___1\file___1_segment_553.mp3
Saved segment 5 to training\me14-brereabbit-43mins\processed\run\dataset\wav_splits\file___1\file___1_segment_558.mp3
Saved segment 6 to training\me14-brereabbit-43mins\processed\run\dataset\wav_splits\file___1\file___1_segment_559.mp3
Saved segment 1 to training\me14-brereabbit-43mins\processed\run\dataset\wav_splits\file___1\file___1_segment_562.mp3
Saved segment 7 to training\me14-brereabbit-43mins\processed\run\dataset\wav_splits\file___1\file___1_segment_560.mp3
Saved segment 2 to training\me14-brereabbit-43mins\processed\run\dataset\wav_splits\file___1\file___1_segment_563.mp3
Saved segment 8 to training\me14-brereabbit-43mins\processed\run\dataset\wav_splits\file___1\file___1_segment_561.mp3
Saved segment 3 to training\me14-brereabbit-43mins\processed\run\dataset\wav_splits\file___1\file___1_segment_564.mp3
Saved segment 4 to training\me14-brereabbit-43mins\processed\run\dataset\wav_splits\file___1\file___1_segment_565.mp3
Saved segment 5 to training\me14-brereabbit-43mins\processed\run\dataset\wav_splits\file___1\file___1_segment_566.mp3
Saved segment 6 to training\me14-brereabbit-43mins\processed\run\dataset\wav_splits\file___1\file___1_segment_567.mp3
Traceback (most recent call last):
  File "C:\Users\Shadow\Downloads\StyleTTS-WebUI\runtime\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shadow\Downloads\StyleTTS-WebUI\runtime\Lib\site-packages\gradio\route_utils.py", line 288, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shadow\Downloads\StyleTTS-WebUI\runtime\Lib\site-packages\gradio\blocks.py", line 1931, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shadow\Downloads\StyleTTS-WebUI\runtime\Lib\site-packages\gradio\blocks.py", line 1516, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shadow\Downloads\StyleTTS-WebUI\runtime\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shadow\Downloads\StyleTTS-WebUI\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Shadow\Downloads\StyleTTS-WebUI\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shadow\Downloads\StyleTTS-WebUI\runtime\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shadow\Downloads\StyleTTS-WebUI\runtime\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shadow\Downloads\StyleTTS-WebUI\webui.py", line 421, in transcribe_other_language_proxy
    merge_segments(merge_dir)
  File "C:\Users\Shadow\Downloads\StyleTTS-WebUI\modules\tortoise_dataset_tools\dataset_whisper_tools\combine_folders.py", line 44, in merge_segments
    os.rmdir(folder_path)  # Remove the original directory after all its segments have been moved
    ^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: './training/me14-brereabbit-43mins\\processed\\run\\dataset/wav_splits\\file___1'

**Comment by 96webbjo** [comment]
I had google drive and icloud syncing on my pc in the background. I turn them both off (ended the processes) and everything worked fine.
