### ISSUE TITLE
espeak not installed on your system

### ISSUE THREAD

**Issue by OskariiiiW** [JarodMica/StyleTTS-WebUI#8]
Traceback (most recent call last):
  File "D:\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\route_utils.py", line 288, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\blocks.py", line 1931, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\blocks.py", line 1516, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TTS\StyleTTS-WebUI\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TTS\StyleTTS-WebUI\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\TTS\StyleTTS-WebUI\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\TTS\StyleTTS-WebUI\venv\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\TTS\StyleTTS-WebUI\webui.py", line 445, in phonemize_files
    process_file(train_text_path, train_opt_path, option)
  File "D:\TTS\StyleTTS-WebUI\modules\tortoise_dataset_tools\dataset_whisper_tools\train_to_phoneme.py", line 32, in process_file
    ipa_text = text_to_ipa(text, language)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TTS\StyleTTS-WebUI\modules\tortoise_dataset_tools\dataset_whisper_tools\train_to_phoneme.py", line 10, in text_to_ipa
    ipa_text = phonemize(
               ^^^^^^^^^^
  File "D:\TTS\StyleTTS-WebUI\venv\Lib\site-packages\phonemizer\phonemize.py", line 206, in phonemize
    phonemizer = BACKENDS[backend](
                 ^^^^^^^^^^^^^^^^^^
  File "D:\TTS\StyleTTS-WebUI\venv\Lib\site-packages\phonemizer\backend\espeak\espeak.py", line 45, in __init__
    super().__init__(
  File "D:\TTS\StyleTTS-WebUI\venv\Lib\site-packages\phonemizer\backend\espeak\base.py", line 39, in __init__
    super().__init__(
  File "D:\TTS\StyleTTS-WebUI\venv\Lib\site-packages\phonemizer\backend\base.py", line 77, in __init__
    raise RuntimeError(  # pragma: nocover
RuntimeError: espeak not installed on your system

It gives me this error when I try to run phonemization, even though I have it installed and it shows up in the programs list in control panel. Even using "espeak-ng hello" in cmd works and I hear a robotic hello. I have the correct version 1.51. Uninstalling it and installing it again doesn't work, and rebooting won't help either. I don't know what else I can do to try to fix it.

**Comment by NathanInArk** [comment]
Ran into this same issue, you will need include espeak in your path system variable. 
Adding these two will fix it.
```
PHONEMIZER_ESPEAK_LIBRARY="c:\Program Files\eSpeak NG\libespeak-ng.dll"
PHONEMIZER_ESPEAK_PATH =“c:\Program Files\eSpeak NG”
```
Stolen from https://github.com/bootphon/phonemizer/issues/44

**Comment by OskariiiiW** [comment]
works now, thanks!

**Comment by theslipperyCarrot** [comment]
Hi!
I´ve installed StyleTTS WebUI yesterday and runned it once with success.
Today i get this Error when trying to start the WebUI.
ESpeakNG is installed and "c:\Program Files\eSpeak NG" was set under systemwide path.
I now added "c:\Program Files\eSpeak NG\libespeak-ng.dll" to path too and restarted my PC.
But the RuntimeError was shown again.

Is it a problem, that i´m not logged into windows as admin?

Beste Regards and Thanks!
Jonas


CMD:
C:\KI\StyleTTS-WebUI>.\venv\Scripts\activate

(venv) C:\KI\StyleTTS-WebUI>python webui.py
C:\KI\StyleTTS-WebUI\venv\Lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
C:\KI\StyleTTS-WebUI\venv\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:43: UserWarning: torchaudio._backend.get_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  backend = torchaudio.get_audio_backend()
C:\Users\Nutzer\AppData\Local\Programs\Python\Python311\Lib\inspect.py:988: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
  if ismodule(module) and hasattr(module, '__file__'):
C:\KI\StyleTTS-WebUI\venv\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:45: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
  from speechbrain.pretrained import (
C:\KI\StyleTTS-WebUI\venv\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:53: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend(backend)
C:\KI\StyleTTS-WebUI\venv\Lib\site-packages\pyannote\audio\tasks\segmentation\mixins.py:37: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path.
  from torchaudio.backend.common import AudioMetaData
C:\KI\StyleTTS-WebUI\venv\Lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
C:\KI\StyleTTS-WebUI\venv\Lib\site-packages\torch\nn\modules\rnn.py:83: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "
Traceback (most recent call last):
  File "C:\KI\StyleTTS-WebUI\webui.py", line 911, in <module>
    main()
  File "C:\KI\StyleTTS-WebUI\webui.py", line 574, in main
    load_all_models(initial_settings["voice_model"])
  File "C:\KI\StyleTTS-WebUI\webui.py", line 82, in load_all_models
    global_phonemizer = load_phonemizer()
                        ^^^^^^^^^^^^^^^^^
  File "C:\KI\StyleTTS-WebUI\venv\Lib\site-packages\styletts2\utils.py", line 164, in load_phonemizer
    global_phonemizer = phonemizer.backend.EspeakBackend(language='en-us', preserve_punctuation=True, with_stress=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\KI\StyleTTS-WebUI\venv\Lib\site-packages\phonemizer\backend\espeak\espeak.py", line 45, in __init__
    super().__init__(
  File "C:\KI\StyleTTS-WebUI\venv\Lib\site-packages\phonemizer\backend\espeak\base.py", line 39, in __init__
    super().__init__(
  File "C:\KI\StyleTTS-WebUI\venv\Lib\site-packages\phonemizer\backend\base.py", line 77, in __init__
    raise RuntimeError(  # pragma: nocover
RuntimeError: espeak not installed on your system

**Comment by emrahtoy** [comment]
In case you are using the Pinokio script please consider following [these steps](https://github.com/JarodMica/StyleTTS-WebUI/issues/2) in the issue. #2
